import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faBars,
  faExclamationCircle,
  faDownload,
  faSave,
  faStar,
  faBook,
  faUserCircle,
  faBell,
  faMoneyBill,
  faCircleCheck,
  faCircleXmark,
  faEye,
  faEyeSlash,
  faCopy,
  faVideoCamera,
  faEdit,
  faCircle,
  faPlusCircle,
  faPencil,
  faTrash,
  faDiamond,
  faArrowTurnUp,
  faFileLines,
} from '@fortawesome/free-solid-svg-icons'
import {
  faTwitter,
  faInstagram,
  faDiscord,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faBars,
  faExclamationCircle,
  faDownload,
  faSave,
  faStar,
  faBook,
  faUserCircle,
  faBell,
  faMoneyBill,
  faCircleCheck,
  faCircleXmark,
  faTwitter,
  faInstagram,
  faEye,
  faEyeSlash,
  faCopy,
  faDiscord,
  faVideoCamera,
  faEdit,
  faCircle,
  faPlusCircle,
  faPencil,
  faTrash,
  faDiamond,
  faArrowTurnUp,
  faFileLines
)
